CC = g++
CXXFLAGS = -std=c++14 -Wall -o
OBJ = P97156_number
all: ${OBJ}
${OBJ}: object_P97156_number
	${CC} ${CXXFLAGS} $@ $@.o
object_P97156_number:
	${CC} -c ${OBJ}.cc
clean:
	rm -f ${OBJ}.o
	rm -f ${OBJ}
